# Generated by Django 2.2.16 on 2023-01-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ingredient', max_length=200, verbose_name='Ingredient')),
                ('measurement_unit', models.CharField(help_text='Enter a ingredient', max_length=200, verbose_name='Ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tag', max_length=200, verbose_name='Tag')),
                ('color', models.CharField(blank=True, help_text='Enter a tag', max_length=7, null=True, verbose_name='Tag')),
                ('slug', models.SlugField(help_text='Enter the tag URL', max_length=200, unique=True, verbose_name='Tag URL')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('is_in_shopping_cart', models.BooleanField(default=False, verbose_name='В корзине')),
                ('name', models.CharField(help_text='Enter a recipe', max_length=200, verbose_name='Recipe')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='Image')),
                ('text', models.TextField(help_text='Добавьте рецепт', verbose_name='Text recipe')),
                ('cooking_time', models.TimeField(verbose_name='Время приготовления (в минутах)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='recipes.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('name',),
            },
        ),
    ]
