# Generated by Django 2.2.16 on 2023-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230124_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
