# Generated by Django 2.2.16 on 2023-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Enter a color', max_length=7, null=True, verbose_name='color'),
        ),
    ]
