# Generated by Django 2.2.16 on 2023-02-04 06:37

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230204_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[users.validators.validate_username], verbose_name='Юзернейм'),
        ),
    ]
