# Generated by Django 2.2.16 on 2023-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230122_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(help_text='Подписан ли текущий пользователь на этого'),
        ),
    ]
