# Generated by Django 2.2.16 on 2023-01-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230122_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_subscribed',
            new_name='subscribed',
        ),
    ]
