# Generated by Django 2.2.16 on 2023-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230122_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Подписан ли текущий пользователь на этого'),
        ),
    ]
